### PR TITLE
Feature: Array.prototype.flat()

### PR DESCRIPTION
**Pull request by Adrian-Benavente**
Use `.flat()` as the modern way to flatten arrays in JS (reference in the notes)

### CODE REVIEW

**Review by Adrian-Benavente — COMMENTED** [review]
Sorry, the commit message for the second one should say `feat(flattenDeep)`, my mistake!

**Comment by cedmax** [comment]
Thanks for the PR! May I ask why do we need corejs? According to MDN flat should be in node starting at v11 and the nvmrc for the project is above 12, unless there is more I missed.

**Comment by cedmax** [comment]
(and don't worry about the commit messages in the PR, I squash it anyway)

**Comment by Adrian-Benavente** [comment]
> Thanks for the PR! May I ask why do we need corejs? According to MDN flat should be in node starting at v11 and the nvmrc for the project is above 12, unless there is more I missed.

I'm glad to contribute!
It's not a problem with node but with Jest, I left the link to the issue on the Jest team repository in the [commit message](https://github.com/cedmax/youmightnotneed/pull/125/commits/8c5edf6617bc77dd7556fdc1fb900a8b2985f373), where they discuss about that. I'll leave you the link here too: https://github.com/kulshekhar/ts-jest/issues/828#issuecomment-433976880 

Otherwise, the test gives "flat() is not a function".
The issue is open at ts-jest but it seems to affect vanilla Jest too.
Thank you!

**Comment by cedmax** [comment]
Thanks for explaining. I will have a look at it (don't hold your breath
though, I might not get around it until Monday)

**Comment by cedmax** [comment]
Hi @Adrian-Benavente, sorry it took me longer than anticipated. 
I tried to run your code without core-js on node v12+ and it works just fine: I don't think that's needed.  If you could reset the `package.json` and the `yarn.lock` we could test it in the build as well. 
As per the rest, it looks good and I look forward to be able to merge it.

**Review by cedmax — CHANGES_REQUESTED** [review]
Hi @Adrian-Benavente, sorry it took me longer than anticipated.
I tried to run your code without `core-js` on node v12+ and it works just fine: I don't think that's needed. If you could reset the `package.json` and the `yarn.lock` we could test it in the build as well.
As per the rest, it looks good and I look forward to be able to merge it.

**Comment by Adrian-Benavente** [comment]
> Hi @Adrian-Benavente, sorry it took me longer than anticipated.
> I tried to run your code without `core-js` on node v12+ and it works just fine: I don't think that's needed. If you could reset the `package.json` and the `yarn.lock` we could test it in the build as well.
> As per the rest, it looks good and I look forward to be able to merge it.

@cedmax Ok, done :)

**Review by cedmax — APPROVED** [review]

**Pull request merged**
