### PR TITLE
kebabcase with more tests than in the official documentation

### PR DESCRIPTION
**Pull request by doydoy44**

### CODE REVIEW

**Review by 102 — COMMENTED** [review]
Does it make sense to propose the extra test cases to the branch from #200?

**Comment by doydoy44** [comment]
@102 Yes, because, if you take the proposal solution of the branch kebabCase:  (https://github.com/cedmax/youmightnotneed/pull/200/files), the cases  "20abcDe" and "30fghIJ" don't work.:
Expected : "20-abc-de" and "30-fgh-ij"
Result : "20abc-de" and "30fghij"

**Comment by 102** [comment]
> @102 Yes, because, if you take the proposal solution of the branch kebabCase: (https://github.com/cedmax/youmightnotneed/pull/200/files), the cases "20abcDe" and "30fghIJ" don't work.: Expected : "20-abc-de" and "30-fgh-ij" Result : "20abc-de" and "30fghij"

so you can change the target branch to `cedmax:kebabCase` and resolve conflicts

**Comment by doydoy44** [comment]
OK,
Out of respect, I didn't want to overwrite the work done, so I created another branch with a new solution.
But you are right, I will make a new commit :)

**Pull request closed without merging**
