### PR TITLE
Added new methods and fixed breaking moment simple format test case

### PR DESCRIPTION
**Pull request by shubhamV123**
Following items in these commits : 
1. Added lodash **get** function 
2. ```new Intl.DateTimeFormat  ``` is not giving the date in which moment formatted the date which causes test failing. Fixed it. ** Solution **: Simply added vanilla date string interpolation

### CODE REVIEW

**Comment by cedmax** [comment]
Hi @shubhamV123, thanks for your contribution.
I have to ask if you could isolate the new implementation from the moment fix: the latter has been tackled in another [PR](https://github.com/cedmax/youmightnotneed/pull/46) which uses a similar approach. I'd love to get the `get` implementation iin 😊

**Comment by shubhamV123** [comment]
@cedmax I can't push the code of because of that test failing that's why I have to add a fix for that code. Either you merge that code to master first. Then I will give you pull request again.

**Comment by cedmax** [comment]
I see, ok I will look into it, thanks for letting me know

Marco

**Comment by shubhamV123** [comment]
Cool. Let me know once it's fixed. If required I will reraise pull request.

**Comment by cedmax** [comment]
Hi @shubhamV123, I removed that test, if you merge master and choose it over your changes you should be able to push the new code without problems

**Comment by shubhamV123** [comment]
@cedmax Rebased my branch with upstream. Now you can merge with **get** code.

**Comment by cedmax** [comment]
Thanks again

**Pull request merged**
