### PR TITLE
fix broken moment format test

### PR DESCRIPTION
**Pull request by tombiju**
- This PR will fix the broken moment format test, resolving this issue: https://github.com/cedmax/youmightnotneed/issues/22
- Changed some `.eslintrc`  rules so that I could demonstrate some native equivalents of lodash methods in their simplest form
- Added a bunch of lodash lang section entries

### CODE REVIEW

**Comment by cedmax** [comment]
Hi @tombiju, thanks a lot for the contribution! 

I was wondering if you could make 2 changes to this PR:
1) split the addition of methods and the fix of the moment test in 2 different PRs
2) change some of the vanilla version to "reimplement" the lodash function rather than inlining the result: e.g. instead of `exports.equalTo = 3 > 3` have something like `const ge = (a, b) => a >b` and then `exports.equalTo = ge(3, 3)`.

I hope my requests make sense and they are not too much to ask :)

**Comment by tombiju** [comment]
@cedmax makes sense! Ok I'll split it so that this PR is just for the moment js test fix and the other one brings in the lodash changes (making sure not to inline the results like you said)

**Comment by tombiju** [comment]
@cedmax broke it apart, let me know what you think of this first PR!

**Comment by cedmax** [comment]
It's an interesting approach but it moves away from invoking a function with a configuration. It would definitely solve the problem but it wouldn't be a drop in replacement for the lodash method, if that makes sense. I need to think about this 🤔

**Comment by cedmax** [comment]
@tombiju please have a look at this: https://github.com/cedmax/youmightnotneed/issues/22#issuecomment-545947957

I will remove this example for the minute and get back to it when I find more, so you can contribute with the other part of your initial PR

**Comment by tombiju** [comment]
@cedmax ok sounds good, thanks! I'll send in the other PR

**Comment by cedmax** [comment]
Thank you! Also please be aware I upgraded the dependencies, you might have to install them again after aligning to master.

**Pull request closed without merging**
