### PR TITLE
Fixed Lodash "min" typo and fixed date-fns Unix-related methods and tests

### PR DESCRIPTION
**Pull request by jpbriggs408**
Hi!

I am updating a few files here to fix a few errors that I noticed. Looking through the date-fns website, it appears that these same errors exist there in their examples.

Let me know if you require anything else to merge this PR. Thanks!

-Jonathan

### CODE REVIEW

**Comment by cedmax** [comment]
Hi, thanks dor your contribution, the examples are lifted from the date-fns codebase, so yes, they should be wrong there too. Anyway, I'm happy to fix it, but right now I'm in a location with limited connectivity, I will pick it up in a couple of weeks, when back.

**Comment by jpbriggs408** [comment]
Of course! No problem. :) Certainly nothing super urgent, but thought that it would be helpful to fix these for anybody who might possibly get confused as to why their code is not consistent with the examples. Definitely take your time!

**Comment by cedmax** [comment]
Hi @jpbriggs408, sorry for the radio silence, I'm back. The fix on the min is defo correct, but could you walk me through the difference between 

`new Date(2012, 1, 29, 11, 45, 5, 123)`
and 
`new Date(Date.UTC(2012, 1, 29, 11, 45, 5, 123))`

I admit my ignorance on the topic, happy to update it if it's a meaningful change, but if it's more of a subtle change I'd rather keep it as it was for "noise reduction" purposes

**Comment by jpbriggs408** [comment]
Hey @cedmax. No problem! Hope that you enjoyed your time away. :)

I would be happy to walk you through the change to the `Date` tests.  So, with the way that the tests were (without having `Data.UTC`), the code actually doesn't pass unless you're in a specific timezone. When creating and testing `Date`s, you want to ensure that the code is able to execute correctly regardless of the timezone of the user. In my case, I am in California, and so the tests were failing since I am seven hours behind UTC time, and thus the outputted time was inconsistent with what was being returned. In my case, I was getting a string that represented `29 February 2012 4:45:05.123` instead of `29 February 2012 11:45:05.123` as desired. This also means that, without this change, anybody who tries to contribute to this code is going to run into the same error if they are in a different time zone and run the test suite.

So what I am doing here is ensuring that the code works no matter where it is run, which is an admittedly subtle change, but an important one!

Here are some Javascript docs to clarify in case I didn't explain that well:

image

**Comment by cedmax** [comment]
I guess this falls straight in my TIL, thank you 😊

**Review by cedmax — APPROVED** [review]

**Comment by cedmax** [comment]
@jpbriggs408 you mind aligning the branch to my main branch? I had to rollback to Travis as circle ci wasn't building it

**Comment by jpbriggs408** [comment]
No problem! Let me know if that worked for ya. :)

**Pull request merged**
