### PR TITLE
Deburr

### PR DESCRIPTION
**Pull request by cedmax**

### CODE REVIEW

**Comment by chimurai** [comment]
Nice vanilla alternative!

Is there a way to handle this use-case?

### Vanilla
```js
const deburr = str => str.normalize('NFD').replace(/[\u0300-\u036f]/g, '')

deburr('Flíeßendes wáßer');  // 'Fließendes waßer'
deburr('ß æ œ ł');  // 'ß æ œ ł'
```

### lodash.deburr
```js
var deburr = require("lodash.deburr");

deburr('Flíeßendes wáßer');  // "Fliessendes wasser"
deburr('ß æ œ ł');  // "ss ae oe l"
```

**Comment by cedmax** [comment]
I have no idea 😅 I'll play with it as soon as I have a minute, thanks for pointing it out

**Comment by chimurai** [comment]
Of course there is this way to achieve the result.  😙

```js
const specialChars = {
  'ß': 'ss',
  'æ': 'ae',
  'œ': 'oe',
  'ł': 'l'
};

let deburr = str => str
  .replace(/[ßæœł]/g, match => specialChars[match])
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '');
```

Wondering if there is an more elegant way to achieve this; like you did with diacritical marks removal.

**Comment by chimurai** [comment]
https://github.com/lodash/lodash/blob/master/test/utils.js#LL108-L123C3

Looking at lodash' tests, these characters are not deburred.

Unicode: `Æ Ð Ø Þ ß æ ð ø þ Đ đ Ħ ħ ı Ĳ ĳ ĸ Ŀ ŀ Ł ł ŉ Ŋ ŋ Œ œ Ŧ ŧ ſ`

youmightnotneed deburr: `Æ Ð Ø Þ ß æ ð ø þ Đ đ Ħ ħ ı Ĳ ĳ ĸ Ŀ ŀ Ł ł ŉ Ŋ ŋ Œ œ Ŧ ŧ ſ`

lodash.deburr: `Ae D O Th ss ae d o th D d H h i IJ ij k L l L l 'n N n Oe oe T t ss`

**Comment by cedmax** [comment]
@chimurai I made a variant of yours (as there are more characters mapping to the same "normalised" letters). 
I think this works reasonably well for the purpose of the site (which is not to provide a drop in replacement, but more of a learning tool)

**Comment by 102** [comment]
@chimurai 
> Looking at lodash' tests, these characters are not deburred.

Fun fact: it seems that lodash does not deburr the capital eszett:
```js
_.deburr('ẞ')
// => 'ẞ' (should be Ss)
'\u1E9E'
// => 'ẞ'
```

This letter was added to unicode quite a long time ago, but it was only added to German orthography back in 2017 🙂

**Comment by cedmax** [comment]
@102 @chimurai I took the exented version list of characters (and the implementation) from: https://stackoverflow.com/a/17694737

I had to remove quite a few as they are not supported by lodash 🤷‍♀️ but ultimately this approach allows for whatever level of flexibility is needed

**Pull request merged**
